bin = "Insira uma bin: "

print('')
print('Gerador de CC (Pros amigos usarem no ifood)')
print('')
print('Escolha o que voce quer fazer')         
print('')

local mes = math.random(1, 12)
local ano = math.random(23, 27)
local cc = math.random(1, 99999)
cartao = io.write('Digite uma das opcoes: ')
local comando = io.read()
io.write(bin)
local bindocard = io.read()
print('')
print('')
print('CC Gerado ')
print('')
print(string.format("Cartao: %s%s", bindocard, cc))
print('CVV: 0000')
print(string.format("Validade: %s do %s", mes, ano))
print('')
print('Caso queira outra e so repetir o processo!')
print('')
os.exit()